### ISSUE TITLE
Pre-trained model files missing

### ISSUE THREAD

**Issue by Mat8e** [rasd3/3D-CVF#8]
Hi, 
Thanks for sharing the code of your method. I am trying to reproduce your results with your code but I am missing the pre-trained weight files you are using to initialize your networks: `pre_weights/FPN18_retinanet_968.pth` and `pre_weight/first_stage/fusion_split/voxelnet-35210.tckpt`.
Is there a way to download those files somewhere or pre-train the networks in a similar way ?

**Comment by DanielZ98** [comment]
Hi, did you find the FPN18_retinanet_968.pth?

**Comment by Mat8e** [comment]
Hi, no I commented the line in the end and started a new training from 0. Apparently, from what I remember from the paper, it is simply a retinanet pretrained on the kitti dataset. You can get close enough from their results without it though. If you managed to come to this stage of the debugging, and want to persevere to reach close results to original implementation, you need to correct the mistake in second/pytorch/models/rpn.py  line 410: 

original: ```box_preds = self.conv_box(bev_feature)```
correction: ```box_preds = self.conv_box(concat_feat)```

After my investigations I still did not manage to find the "pointnet" used for the feature pooling and it is an annoying mystery. However with that correction you become very close to their results (~1-2%) without even using the second stage.
Good luck !

**Comment by DanielZ98** [comment]
Thanks a lot

**Comment by mc171819** [comment]
hi, i want to ask that did you have some mistake in 3D-CVF/second/core/box_np_ops.py when run from spconv.utils import rbbox_iou, rbbox_iou_loss. I can't import rbbox_iou_loss correctly. Did you meet this problem?

**Comment by mc171819** [comment]
> Hi, no I commented the line in the end and started a new training from 0. Apparently, from what I remember from the paper, it is simply a retinanet pretrained on the Kitti dataset. If you managed to come to this stage of the debugging, and want to persevere to reach close results to the one advertised in the paper, you need to correct the mistake in second/pytorch/models/rpn.py line 410:
> 
> original: `box_preds = self.conv_box(bev_feature)` correction: `box_preds = self.conv_box(concat_feat)`
> 
> After my investigations I still did not manage to find the "pointnet" used for the feature pooling and it is an annoying mystery. However with that correction you become very close to their results (~1-2%) without even using the second stage nor the pertained retinanet. Good luck !

hi, when you run this code did you find many bugs? will you mind sending me the code you run successfully? thank you very much!

**Comment by FANGZHENGFA** [comment]
> Hi, no I commented the line in the end and started a new training from 0. Apparently, from what I remember from the paper, it is simply a retinanet pretrained on the Kitti dataset. If you managed to come to this stage of the debugging, and want to persevere to reach close results to the one advertised in the paper, you need to correct the mistake in second/pytorch/models/rpn.py line 410:
> 
> original: `box_preds = self.conv_box(bev_feature)` correction: `box_preds = self.conv_box(concat_feat)`
> 
> After my investigations I still did not manage to find the "pointnet" used for the feature pooling and it is an annoying mystery. However with that correction you become very close to their results (~1-2%) without even using the second stage nor the pertained retinanet. Good luck !

Hi，
how to starte a new training from 0?
sincerely.

**Comment by guzuoxu** [comment]
> 

Hi! Could you provide more details?

**Comment by FANGZHENGFA** [comment]
> 



> > 
> 
> Hi! Could you provide more details?

I just commented the code of pre-train-model-load, and train from 0

**Comment by guzuoxu** [comment]
> > 
> 
> > > 
> > 
> > 
> > Hi! Could you provide more details?
> 
> I just commented the code of pre-train-model-load, and train from 0

Thank you! I understand what you mean. In addition, when you are training 3DCVF, is the pkl file generation method on the kitti dataset the same as the second generation method?

**Comment by FANGZHENGFA** [comment]
> > > 
> > 
> > 
> > > > 
> > > 
> > > 
> > > Hi! Could you provide more details?
> > 
> > 
> > I just commented the code of pre-train-model-load, and train from 0
> 
> Thank you! I understand what you mean. In addition, when you are training 3DCVF, is the pkl file generation method on the kitti dataset the same as the second generation method?

It depends on the version of SECOND.
3D-CVF's pkl files is the same as SECOND v1.5. You can follow the README file in SECONDv1.5 and generate the pkl files.
The pkl of SECOND-master(and v1.5.1) is different to 3D-CVF.

**Comment by guzuoxu** [comment]
> 

I got it, thank you very much for your reply！

**Comment by jiangliangliang2020** [comment]
> > 
> 
> I got it, thank you very much for your reply！

Hi,I commented the code of pre-train-model-load,but I am missing this file: KITTI/object/gt_database/7392_Car_2.bin.Did you meet this problem?

**Comment by jiangliangliang2020** [comment]
> > 
> 
> I got it, thank you very much for your reply！

Hi,I commented the code of pre-train-model-load,but I am missing this file: KITTI/object/gt_database/7392_Car_2.bin.Did you meet this problem?

**Comment by guzuoxu** [comment]
> > > 
> > 
> > 
> > I got it, thank you very much for your reply！
> 
> Hi,I commented the code of pre-train-model-load,but I am missing this file: KITTI/object/gt_database/7392_Car_2.bin.Did you meet this problem?

No, I did not encounter this problem. If there is a missing file, how about adding this file to the corresponding folder?
![微信图片_20211203094519](https://user-images.githubusercontent.com/57511889/144530730-ba3c4721-ea20-4922-9f4d-c3296be9cb2f.png)

**Comment by jiangliangliang2020** [comment]
Thank you very much for your reply. How did you get the car.bin file?



---Original---
From: ***@***.***&gt;
Date: Fri, Dec 3, 2021 09:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rasd3/3D-CVF] Pre-trained model files missing (#8)




     
I got it, thank you very much for your reply！
  
Hi,I commented the code of pre-train-model-load,but I am missing this file: KITTI/object/gt_database/7392_Car_2.bin.Did you meet this problem?
  
No, I did not encounter this problem. If there is a missing file, how about adding this file to the corresponding folder?
 
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guzuoxu** [comment]
> 

Did you follow create_data.py in sencond1.5 to generate data?

**Comment by jiangliangliang2020** [comment]
I git it，Thank you very much！



---Original---
From: ***@***.***&gt;
Date: Fri, Dec 3, 2021 10:36 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rasd3/3D-CVF] Pre-trained model files missing (#8)




   
Did you follow create_data.py in sencond1.5 to generate data?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qrzeffort** [comment]
> > > 
> > 
> > 
> > > > 
> > > 
> > > 
> > > Hi! Could you provide more details?
> > 
> > 
> > I just commented the code of pre-train-model-load, and train from 0
> 
> Thank you! I understand what you mean. In addition, when you are training 3DCVF, is the pkl file generation method on the kitti dataset the same as the second generation method?

Hi，I modified code according to the steps in issue, but it didn't succeed.Now,I wonder what the "train from 0" mean?

**Comment by qrzeffort** [comment]
And I occurred error：

Traceback (most recent call last):
  File "pytorch/train.py", line 691, in <module>
    fire.Fire()
  File "/home/nn/anaconda3/envs/3dcvf/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/nn/anaconda3/envs/3dcvf/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/nn/anaconda3/envs/3dcvf/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "pytorch/train.py", line 416, in train
    raise e
  File "pytorch/train.py", line 250, in train
    example = next(data_iter)
  File "/home/nn/anaconda3/envs/3dcvf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/nn/anaconda3/envs/3dcvf/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/nn/anaconda3/envs/3dcvf/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/nn/anaconda3/envs/3dcvf/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/nn/anaconda3/envs/3dcvf/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nn/anaconda3/envs/3dcvf/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nn/3D-CVF/second/pytorch/builder/input_reader_builder.py", line 18, in __getitem__
    return self._dataset[idx]
  File "/home/nn/3D-CVF/second/data/dataset.py", line 70, in __getitem__
    prep_func=self._prep_func)
  File "/home/nn/3D-CVF/second/data/preprocess.py", line 344, in _read_and_prep_v9
    example = prep_func(input_dict=input_dict)
  File "/home/nn/3D-CVF/second/data/preprocess.py", line 204, in prep_pointcloud
    gt_boxes, points = prep.random_flip(gt_boxes, points)
ValueError: too many values to unpack (expected 2)

I tried to modify the config and data files，but it didn't succeed. Can someone help me？

**Comment by zijianh4** [comment]
> create

Hi, do you solve this problem? I use the create_data.py from SECOND-1.5 but it seems not correct. Thanks!

**Comment by zijianh4** [comment]
> Did you follow create_data.py in sencond1.5 to generate data?

Hi, do you solve this problem? I use the create_data.py from SECOND-1.5 but it seems not correct. Thanks!
