### ISSUE TITLE
ModuleNotFoundError: No module named 'iou3d_nms_cuda'

### ISSUE THREAD

**Issue by jackyyang-cv** [rasd3/3D-CVF#9]
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from second.builder import target_assigner_builder, voxel_builder
  File "/home/codes/deeplearn/3d/3D-CVF/second/builder/target_assigner_builder.py", line 3, in <module>
    from second.core.target_assigner import TargetAssigner
  File "/home/codes/deeplearn/3d/3D-CVF/second/core/target_assigner.py", line 1, in <module>
    from second.core import box_np_ops
  File "/home/codes/deeplearn/3d/3D-CVF/second/core/box_np_ops.py", line 5, in <module>
    from second.core.non_max_suppression.nms_gpu import rotate_iou_gpu_eval
  File "/home/codes/deeplearn/3d/3D-CVF/second/core/non_max_suppression/__init__.py", line 2, in <module>
    from second.core.non_max_suppression.nms_gpu import (nms_gpu, rotate_iou_gpu,
  File "/home/codes/deeplearn/3d/3D-CVF/second/core/non_max_suppression/nms_gpu.py", line 11, in <module>
    import iou3d_nms_cuda
ModuleNotFoundError: No module named 'iou3d_nms_cuda'

I use the envirment "docker pull yckimm/second:second_v1.5", and get this error. 
could you fix it

**Comment by Mat8e** [comment]
Hi,

Launching this repo requires additional installation not mentioned in the instructions.
For this issue you need to install [OpenPCDet](https://github.com/open-mmlab/OpenPCDet) and follow the INSTALL.md instructions. 

Then you need to change line 10 of `second/core/non_max_suppression/nms_gpu.py` with the path relative to your OpenPCDet installation : `sys.path.append('/<your path to OpenPCDet parent directory>/PCDet/pcdet/ops/iou3d_nms')`

**Comment by RickOnEarth** [comment]
Hi, have you faced the problem   
`from spconv.utils import rbbox_iou, rbbox_iou_loss
ImportError: cannot import name 'rbbox_iou_loss'`  ?
 Could you tell me which spconv version you used? I have tried all the spconv various, but none of them applys 'rbbox_iou_loss'.
